### ISSUE TITLE
Attribute is displayed in an incorrect skill

### ISSUE THREAD

**Issue by lordpegason** [Gardios/ToS-Addons#2]
The Skill Frost Cloud is displayed incorrectly with the Skill Freezing Sphere attribute.

Bug below:

![bug01](https://cloud.githubusercontent.com/assets/19753518/15802363/92198abe-2a85-11e6-8717-9f19b4038788.png)

Already Skill Freezing Sphere is not the attribute displays

Bug 2 below:

![bug 02](https://cloud.githubusercontent.com/assets/19753518/15802366/9eb63902-2a85-11e6-9e76-17a3e9868346.png)

**Comment by Gardios** [comment]
That bug's on IMC. Freezing Sphere: Enhance is (falsely) classified as an attribute for Frost Cloud, which is why it's displayed there and not on Freezing Sphere. We have to wait for IMC to fix that.

I also can't have the addon check for the displayed name to catch those errors. While that would fix this issue in particular, there are other attributes that are wrongly named, meaning that you'd get new errors in return.
